### ISSUE TITLE
Secret UI in each device/virtual machine

### ISSUE THREAD

**Issue by jk-onnet** [DanSheps/netbox-secretstore#10]
In NetBox 3.0.0, the Secret UI is not appeared in device/virtual machine display field as old version. Is this expected behavior?

**Comment by DanSheps** [comment]
Can you give an example?

On Sep. 7, 2021 20:38, jk-onnet ***@***.***> wrote:

In NetBox 3.0.0, the Secret UI is not appeared in device/virtual machine display field as old version. Is this expected behavior?

**Comment by jk-onnet** [comment]
In NetBox version 3.0.1
I'm using netbox_secretstore API to create the secret. 

Secret created 
<img width="702" alt="secret created" src="https://user-images.githubusercontent.com/85537520/132654197-6c0abef8-b904-46ff-b4c6-e50845daff04.PNG">

Missing secret UI 
<img width="864" alt="Missing Secret" src="https://user-images.githubusercontent.com/85537520/132654187-e59bae50-168c-4c42-8ebf-cf09ff2fd91f.PNG">

Expected result
<img width="864" alt="Expected Secret Output" src="https://user-images.githubusercontent.com/85537520/132654696-f20d7a11-e986-4e72-848d-b68b0b3e371b.png">

It is hard to navigate and find each device/virtual machine secret.
