### ISSUE TITLE
Version 1.3.0 is not compatible with Netbox V3.4-beta1

### ISSUE THREAD

**Issue by pdenessen** [DanSheps/netbox-secretstore#101]
### Plugin version

v1.3.0

### NetBox version

v3.4-beta1

### Python version

3.8

### Steps to Reproduce

1. Install Netbox v3.3.7
2. Install the plugin
3. Upgrade netbox via the usual upgrade steps to V3.4-beta1

### Expected Behavior

Netbox should upgrade to the new version

### Observed Behavior

Upgrade script fails with the message that the plugin requires Netbox Maximum Version 3.3.9

**Comment by 1358** [comment]
There are breaking changes in 3.4: https://github.com/netbox-community/netbox/releases/tag/v3.4.0
