### ISSUE TITLE
Migration from NetBox 2.x with secrets

### ISSUE THREAD

**Issue by Peter2121** [DanSheps/netbox-secretstore#36]
### Plugin version

N/A

### netbox-plugin-extensions version

N/A

### NetBox version

v2.10.10

### Feature type

New functionality

### Proposed functionality

It would be nice to have a document explaining the migration from core NetBox v2.x 'secrets' app to this plugin.

### Use case

Existing NetBox installation v2.10.10 with some secrets, how to migrate to NetBox v3.x with this plugin?

**Comment by DanSheps** [comment]
There is already documentation regarding installation.  Migration happens automatically and no additional documentation is required.
