### ISSUE TITLE
Best way to install the module

### ISSUE THREAD

**Issue by tbnobody** [DanSheps/netbox-secretstore#4]
What is the prefered way to install this module?

I added the following to the local_requirements.txt file
`git+https://github.com/DanSheps/netbox-secretstore.git`
used pip install -r local_requirements.txt to install the module and run the migrations.

Problem is, that it seems that the templates are not copied.

I am getting the following Server Error:
```
<class 'django.template.exceptions.TemplateDoesNotExist'>

netbox_secretstore/generic/object_list.html

Python version: 3.9.2
NetBox version: 3.0.1
```

ls -lach /opt/netbox/venv/lib/python3.9/site-packages/netbox_secretstore

shows:
```
drwxr-xr-x  10 root root 4.0K Sep  2 02:10 .
drwxr-xr-x 161 root root  12K Sep  2 02:10 ..
-rw-r--r--   1 root root 2.5K Sep  2 02:10 admin.py
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 api
-rw-r--r--   1 root root  217 Sep  2 02:10 constants.py
-rw-r--r--   1 root root   97 Sep  2 02:10 exceptions.py
-rw-r--r--   1 root root 2.1K Sep  2 02:10 filters.py
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 forms
-rw-r--r--   1 root root  386 Sep  2 02:10 hashers.py
-rw-r--r--   1 root root  535 Sep  2 02:10 __init__.py
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 migrations
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 models
-rw-r--r--   1 root root 2.3K Sep  2 02:10 navigation.py
drwxr-xr-x   2 root root 4.0K Sep  2 02:10 __pycache__
-rw-r--r--   1 root root  334 Sep  2 02:10 querysets.py
-rw-r--r--   1 root root 1.5K Sep  2 02:10 tables.py
-rw-r--r--   1 root root  411 Sep  2 02:10 template_content.py
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 templatetags
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 tests
-rw-r--r--   1 root root 2.2K Sep  2 02:10 urls.py
drwxr-xr-x   3 root root 4.0K Sep  2 02:10 utils
-rw-r--r--   1 root root  11K Sep  2 02:10 views.py
```

**Comment by hiddenman** [comment]
Hi,

I've got the same problem, does not work on the latest 3.0.1 release.

**Comment by DanSheps** [comment]
This was a result of the MANIFEST.in file not being setup properly.  It has been pushed and is also available on PyPi now.

**Comment by tbnobody** [comment]
I can confirm that its working now. Just added `netbox-secretstore` to the `local_requirements.txt` file, Executed `pip install -r local_requirements.txt --upgrade` (important is the correct venv) and executed `manage.py collectstatic`
