### ISSUE TITLE
Secrets in device/virtual machine view

### ISSUE THREAD

**Issue by jk-onnet** [DanSheps/netbox-secretstore#46]
### Plugin version

v1.0.8

### netbox-plugin-extensions version

v1.0.4

### NetBox version

v3.0.8

### Python version

3.8

### Steps to Reproduce

Can I ask is the device and VM secret store view is back? For myself,
Version:
netbox_secretstore==1.0.8
netbox==3.0.8
Because 1.0.0-1.0.5 is yanked, 1.0.6 and 1.0.8 is available while 1.0.7 is missing in pypi. 
I opened this issue #10 , I see #32 face the same issue as me. Any method to integrate the new developed or solved code? I don't know how NetBox plugin works and its installed directory.

### Expected Behavior

Secret table view in Device and Virtual machine Page (facilitating navigation)

### Observed Behavior

Don't have secret table view in Device and Virtual machine Page (facilitating navigation)

**Comment by DanSheps** [comment]
Are you actually running 1.0.8 of secrets?

**Comment by jk-onnet** [comment]
The issue still exist even I updated to 1.0.8, I use local_requirements and run ./upgrade.sh to update.
![image](https://user-images.githubusercontent.com/85537520/142593823-1a40dc22-57b9-4c15-bd8e-92b8d98023de.png)
In timeline of:
#10 I thought it is solved, but I upgrade to 1.0.2 and 1.0.3, the issue still exist.
I see other raise up this issue again during 1.0.4-1.0.8, 
As #44 said, I remember I use this version immediately since you bring up 1.0.8 version, and then their is 1.0.7 at that time but it is not available in pypi, I think it's past month ago. I raise this issue again because I may need the plugin and test the api now . Thanks for the plugins.

**Comment by DanSheps** [comment]
You know what?  It looks like it doesn't like it didn't take the version...

I will see if I can refresh the version today.

**Comment by DanSheps** [comment]
Try the latest PyPi package please

**Comment by jk-onnet** [comment]
Unfortunately, virtual machine secret views is not appeared yet, but the device secret is appeared
