### ISSUE TITLE
HTML Output when unlock secret

### ISSUE THREAD

**Issue by skalec** [DanSheps/netbox-secretstore#50]
### Plugin version

v1.0.10

### netbox-plugin-extensions version

v.1.0.2

### NetBox version

v3.0.10

### Python version

3.8

### Steps to Reproduce

Unlook a secret

### Expected Behavior

Unlook a secret

### Observed Behavior

HTMP popup output

`<head>
<title>Server Error</title>
<link rel="stylesheet" href="/static/netbox-light.css" />
<meta charset="UTF-8">
</head>

<body>
<div class="container-fluid">
<div class="row">
<div class="col col-md-6 offset-md-3">
<div class="card border-danger mt-5">
<h5 class="card-header">
<i class="mdi mdi-alert"></i> Server Error
</h5>
<div class="card-body">

<p>
There was a problem with your request. Please contact an administrator.
</p>

<hr />
<p>
The complete exception is provided below:
</p>
<pre><strong>&lt;class &#x27;UnicodeDecodeError&#x27;&gt;</strong><br />
&#x27;utf-8&#x27; codec can&#x27;t decode byte 0xb2 in position 3: invalid start byte

Python version: 3.8.10
NetBox version: 3.0.10</pre>
<p>
If further assistance is required, please post to the <a href="https://github.com/netbox-community/netbox/discussions">NetBox discussion forum</a> on GitHub.
</p>
<div class="text-end">
<a href="/" class="btn btn-primary">Home Page</a>
</div>
</div>
</div>
</div>
</div>
</div>
</body>

</html>`

**Comment by DanSheps** [comment]
This is due to the secret being un-encrypted when saved.  Most likely due to the fact that the sessionkey wasn't generated.
