### ISSUE TITLE
Problem with installing the latest netbox-secretstore plugin

### ISSUE THREAD

**Issue by kamilzelazny** [DanSheps/netbox-secretstore#53]
### Plugin version

v1.0.11

### netbox-plugin-extensions version

v1.0.8

### NetBox version

v3.1.0

### Python version

3.8

### Steps to Reproduce

1. source /opt/netbox/venv/bin/activate
2. pip install -r local_requirements.txt --upgrade
3. cd /opt/netbox/netbox/
4. python3 manage.py migrate

### Expected Behavior

Install the latest netbox-secretstore plugin.

### Observed Behavior

Hi,

when I wanted to install the latest netbox-secretstore plugin I received an error:

Your models in app(s): 'netbox_secretstore' have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

HTML output (when I go to the Plugins -> Netbox Secret Store -> Secret Roles or Secrets):

![image](https://user-images.githubusercontent.com/40167146/145436294-8b491218-1b1c-4eee-8041-0c74eed69d12.png)

**Comment by DonMusto** [comment]
Can confirm I am receiving the same.

![20212109-netbox_secretstore-servererror](https://user-images.githubusercontent.com/4002548/145454612-10c21a0b-f126-4138-aaec-01b39ddcfe67.PNG)

**Comment by abhi1693** [comment]
I solved this by adding `netbox_plugin_extensions` to the `PLUGINS`

**Comment by DanSheps** [comment]
`netbox_plugin_extensions` is now required to be loaded.

**Comment by kamilzelazny** [comment]
Thanks!

Adding netbox_plugin_extensions to the Plugins resolved the problem.

**Comment by DonMusto** [comment]
I just wanted to jump in and say for anyone else's benefit that I had to set `DEVELEOPER = True` in configuration.py and then run the following under netbox/netbox:

`python3 manage.py makemigrations
python3 manage.py migrate`

It absolutely refused to work prior.

**Comment by DanSheps** [comment]
You should not, under any circumstance, be making any migrations by yourself.  You should only be running the migrate command, not the makemigrations command.

Doing so, if it creates any new migrations, will compromise the migration chain and will make your specific instance un-upgradable.

**Comment by DonMusto** [comment]
Lol, fantastic, restoring from backup it is.
