### ISSUE TITLE
User Key Generation

### ISSUE THREAD

**Issue by mttws** [DanSheps/netbox-secretstore#54]
### Plugin version

v1.0.11

### netbox-plugin-extensions version

v1.0.8

### NetBox version

v3.1.0

### Python version

3.8

### Steps to Reproduce

Hello. I can't create an user key and returns this error

Steps to reproduce: Navigation Menu > Plugins > User Key > Create a User Key

URL: https://localhost/plugins/netbox_secretstore/user-key/edit/

Environment:
Ubuntu Server 20.04
Python 3.8.10
PostgreSQL 102.9
Redis server v=5.0.7
NetBox version: 3.1.0

### Expected Behavior

Generate an User Key

### Observed Behavior

![image](https://user-images.githubusercontent.com/50388085/145623206-b79bb0b7-e889-45a0-880d-bb07f5ac81cd.png)

**Comment by DanSheps** [comment]
You need to add netbox_plugin_extensions to your PLUGINS.
