### ISSUE TITLE
Plugin not working in netbox 3.1.2

### ISSUE THREAD

**Issue by rmuehl** [DanSheps/netbox-secretstore#57]
### Plugin version

v1.0.11

### netbox-plugin-extensions version

v1.0.8

### NetBox version

v3.1.2

### Python version

3.9

### Steps to Reproduce

python3 netbox/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_secretstore, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_secretstore' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

### Expected Behavior

Should install.

### Observed Behavior

Leads to a 500 Server Error

**Comment by DanSheps** [comment]
Can you post:

`dir ./venv/lib/python3.x/site-packages/netbox_secretstore/migrations/`

make sure you change python3.x to whatever version you are running.  I just pulled down from pipy and I am not seeing any issues.

Can you also upload the models/*.py from your instance please?

**Comment by rmuehl** [comment]
This is the directory listing:
`0001_initial.py  0002_rename_table.py  0003_modify_objectchange_records.py  __init__.py  __pycache__`

My netbox instance is a fresh extraction of netbox-3.1.2.tar.gz with no changes at all (beside the configuration.py).

**Comment by rmuehl** [comment]
And these arethe files from models/*.py
[__init__.py.gz](https://github.com/DanSheps/netbox-secretstore/files/7756512/__init__.py.gz)
[secrets.py.gz](https://github.com/DanSheps/netbox-secretstore/files/7756514/secrets.py.gz)

**Comment by kzelazny90** [comment]
Hi,

I don't want to create next case, but when I want to access Secret Roles or Secrets using web page I got such errors:

[image](https://user-images.githubusercontent.com/81315577/147071875-7ae8927e-bdcc-428c-a25c-3fcd56e23efa.png)

Plugin version
v1.0.11
netbox-plugin-extensions version
v1.0.8
NetBox version
v3.1.2
Python version
3.8

**Comment by itsgottabered** [comment]
I am also getting the error seen above.

<class 'django.template.exceptions.TemplateDoesNotExist'>

inc/table_controls.html

Python version: 3.9.5
NetBox version: 3.1.2
netbox-plugin-extensions version: 1.0.8
netbox-secretstore version: 1.0.11

netbox_1               | 10.0.93.230 - - [04/Jan/2022:05:33:30 +0000] "GET /plugins/netbox_secretstore/secret-roles/ HTTP/1.1" 500 1605 "http://<redacted>:8000/plugins/netbox_secretstore/secrets/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"

**Comment by rmuehl** [comment]
Same problem with netbox 3.1.4

**Comment by rmuehl** [comment]
With version 1.1.1 of netbox_plugin_extensions it's back to work.
