### ISSUE TITLE
RSA generate endpoint does not support key size of 256

### ISSUE THREAD

**Issue by abhi1693** [DanSheps/netbox-secretstore#69]
### Plugin version

v1.0.16

### netbox-plugin-extensions version

None

### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

Send a request to `http://localhost:8000/api/plugins/netbox_secretstore/generate-rsa-key-pair/?key_size=256` and inspect the response

### Expected Behavior

The response should contain the data generated using `256` key size

### Observed Behavior

The key size used is `2048`

**Comment by DanSheps** [comment]
Did you post or get?

**Comment by abhi1693** [comment]
I did `GET` request

**Comment by DanSheps** [comment]
> The response should contain the data generated using 256 key size

256 is not a valid value for RSA, modulus must be at least 1024.
