### ISSUE TITLE
Unable to add user key from the admin panel

### ISSUE THREAD

**Issue by abhi1693** [DanSheps/netbox-secretstore#71]
### Plugin version

v1.0.16

### netbox-plugin-extensions version

None

### NetBox version

v3.2.1

### Python version

3.8

### Steps to Reproduce

The admin panel does not let a selection for the user in the add form.

### Expected Behavior

I have a few bot accounts on NetBox which do not have a usable password so we cannot log in as them to add the user key. However, as a superuser, I should be able to update their user keys to the database.

### Observed Behavior

Unable to select the user from the admin form to add the user key

**Comment by DanSheps** [comment]
This is not supported and you would need to open a feature request however it is unlikely any new features will be added
