### ISSUE TITLE
Cannot use secretstore plugin with pynetbox

### ISSUE THREAD

**Issue by uedvt359** [DanSheps/netbox-secretstore#78]
### Plugin version

v1.0.14

### netbox-plugin-extensions version

v1.1.1

### NetBox version

v3.1.6

### Feature type

Change to existing functionality

### Proposed functionality

Since the secret store was removed from Netbox itself, it is not possible any more to access it through [pynetbox](https://github.com/netbox-community/pynetbox). There are two reasons:

- pynetbox cannot access URLs with underscores in them (as underscores are replaced with dashes; there are no underscore URLs in Netbox)
- pynetbox had special handling for the built-in secret store to pass along the session-key/private-key. there is no such mechanism for plugins.

I had written a [patch to support this plugin](https://github.com/netbox-community/pynetbox/pull/430) in pynetbox, but the developers [seem uninterested in it](https://github.com/netbox-community/pynetbox/issues/425#issuecomment-1100715675).

my hope is that we can work something out how to improve interoperability between this plugin and pynetbox. I'm happy to submit patches once we find a way forward.

### Use case

We were using the secret store in Netbox 2.x, and now with Netbox 3.x. Since NB3.x, it is impossible to use the session store with the python API.

**Comment by DanSheps** [comment]
You are on a old version of NetBox and secrets, please try upgrading.

Also, you need to access it through the plugins namespace

**Comment by uedvt359** [comment]
> You are on a old version of NetBox and secrets, please try upgrading.

We know and are working on it ;) That said, this has not been addressed in the current version (see the open ticket).

> Also, you need to access it through the plugins namespace

this doesn't work, since the plugin uses an underscore in its URLs. Pynetbox replaces underscrores with dashes, so it can build requests out of nested objects with `__getattr__()`. See [here](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/app.py#L179) or [here](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L45-L53).

**Comment by DanSheps** [comment]
Unfortunately, it sounds like pynetbox made a design decision which is negatively impacting you, but that has nothing to do with this plugin.  I suggest you raise the issue with that team.
