### ISSUE TITLE
Secretstore adding User-Key - 'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by jaeyoungh** [DanSheps/netbox-secretstore#79]
### Plugin version

v1.2.0

### netbox-plugin-extensions version

v1.0.2

### NetBox version

v3.2.3

### Python version

3.9

### Steps to Reproduce

1. Login to netbox
2. Navigate to https://netbox.hostname/plugins/netbox_secretstore/user-key/
3. When attempting to add user-key, observe the following error.

### Expected Behavior

Should add the user's public key using the secretstore plugin function.

### Observed Behavior

Server error is returned, with messages below.

`AttributeError at /plugins/netbox_secretstore/user-key/edit/ 'str' object has no attribute '_meta'`

![image](https://user-images.githubusercontent.com/102309322/168643229-2067f67c-320b-4236-a058-5ac4b5801c74.png)

traceback from debug mode: [traceback.log](https://github.com/DanSheps/netbox-secretstore/files/8701903/traceback.log)

**Comment by joebus** [comment]
Had the same issue, mine seemed to be the RSA key I was using.


Try using the following set to 2048 length 
https://cryptotools.net/rsagen

**Comment by jaeyoungh** [comment]
Thanks! that worked. Weird since the key I was trying to add was just openssh for windows.
