### ISSUE TITLE
naming of theplugin

### ISSUE THREAD

**Issue by TheKingOfChaos** [DanSheps/netbox-secretstore#8]
NetBox version

v3.0.1

Plugin Version

v1.0.1

Feature type

Extend existing functionality

Proposed functionality

Hi,
i will like if the plugin and the installer use the same name
ind the configuration.py you are using netbox_secretstore as the name
and in the local_requirements.txt you use netbox-secretstore can we please have it be one ore the other
so it will be easy to install

Database changes

No response

External dependencies

No response

**Comment by DanSheps** [comment]
Hello,

This is similar to other apps within the django ecosystem, for example:

```
django-filter: django_filters
django-tables2: django_tables2
etc
```

As the name was already chosen and deployed, it is unlikely we will update it.
