### ISSUE TITLE
Secretstore adding User-Key - 'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by vermin40** [DanSheps/netbox-secretstore#85]
### Plugin version

1.2.0

### NetBox version

3.2.7

### Python version

3.9

### Steps to Reproduce

Login to netbox
Navigate to https://netbox.hostname/plugins/netbox_secretstore/user-key/
When attempting to add user-key, observe the following error.
netbox-docker-netbox-1               | 10.1.25.34 - - [25/Jul/2022:18:17:21 +0000] "GET /static/netbox_secretstore/secrets.js HTTP/1.1" 200 7722 "https://netbox.merlion.ru/plugins/netbox_secretstore/user-key/edit/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
netbox-docker-netbox-1               | Internal Server Error: /plugins/netbox_secretstore/user-key/edit/
netbox-docker-netbox-1               | Traceback (most recent call last):
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
netbox-docker-netbox-1               |     response = get_response(request)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
netbox-docker-netbox-1               |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
netbox-docker-netbox-1               |     return self.dispatch(request, *args, **kwargs)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_secretstore/views.py", line 269, in dispatch
netbox-docker-netbox-1               |     return super().dispatch(request, *args, **kwargs)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
netbox-docker-netbox-1               |     return super().dispatch(request, *args, **kwargs)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 119, in dispatch
netbox-docker-netbox-1               |     return handler(request, *args, **kwargs)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_secretstore/views.py", line 289, in post
netbox-docker-netbox-1               |     return render(request, self.template_name, {
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
netbox-docker-netbox-1               |     content = loader.render_to_string(template_name, context, request, using=using)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
netbox-docker-netbox-1               |     return template.render(context, request)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
netbox-docker-netbox-1               |     return self.template.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
netbox-docker-netbox-1               |     return self._render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
netbox-docker-netbox-1               |     return self.nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
netbox-docker-netbox-1               |     return compiled_parent._render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
netbox-docker-netbox-1               |     return self.nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
netbox-docker-netbox-1               |     return compiled_parent._render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
netbox-docker-netbox-1               |     return self.nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
netbox-docker-netbox-1               |     return compiled_parent._render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/test/utils.py", line 111, in instrumented_test_render
netbox-docker-netbox-1               |     return self.nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
netbox-docker-netbox-1               |     result = block.nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
netbox-docker-netbox-1               |     return nodelist.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
netbox-docker-netbox-1               |     return SafeString("".join([node.render_annotated(context) for node in self]))
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
netbox-docker-netbox-1               |     return self.render(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 1059, in render
netbox-docker-netbox-1               |     output = self.filter_expression.resolve(context)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 739, in resolve
netbox-docker-netbox-1               |     new_obj = func(obj, *arg_vals)
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/utilities/templatetags/builtins/filters.py", line 79, in meta
netbox-docker-netbox-1               |     return getattr(model._meta, attr, '')
netbox-docker-netbox-1               | AttributeError: 'str' object has no attribute '_meta'

### Expected Behavior

I want add user key to NetBox

### Observed Behavior

I don't create user key

**Comment by vittore** [comment]
+1

**Comment by vermin40** [comment]
Im sorry! Im wrong writes public key:
I have in format:
"-----BEGIN PUBLIC KEY----- 
-----END PUBLIC KEY-----"
But need format:
"-----BEGIN RSA PUBLIC KEY----- 
-----END RSA PUBLIC KEY-----"
Its work )

**Comment by vittore** [comment]
Not resolve for me.

**Comment by danielsilvapereira** [comment]
I have the same problem, I tried to use as you mentioned but no problem at all

**Comment by DanSheps** [comment]
Make sure you are using:

1. Your public key to save the UserKey
2. Your private key for decryption
3. A 2048 or longer key
