### ISSUE TITLE
get-session-key API doesn't work

### ISSUE THREAD

**Issue by mikat-gh** [DanSheps/netbox-secretstore#91]
### Plugin version

v1.3.0

### NetBox version

v3.3.4

### Python version

3.9

### Steps to Reproduce

Hi,

I can't figure how to get our API secret generation working with the secretstore plugin, It worked with Netbox v2.11 integrated secrets. Trying to get session key fails.

First tried just changing the API endpoint to /api/plugins/netbox_secretstore/get-session-key/ this returns:
`"detail": "Unsupported media type \"application/x-www-form-urlencoded\" in request."`

Then tried /api/plugins/netbox_secretstore/secrets/get-session-key/ from <https://github.com/DanSheps/netbox-secretstore/blob/develop/docs/rest-api/working-with-secrets.md> this returns:
`"detail": "Method \"POST\" not allowed."`

The exact example from above docs with just correct token fails also.

### Expected Behavior

New session key returned.

### Observed Behavior

/api/plugins/netbox_secretstore/get-session-key/
`"detail": "Unsupported media type \"application/x-www-form-urlencoded\" in request."`

/api/plugins/netbox_secretstore/secrets/get-session-key/
`"detail": "Method \"POST\" not allowed."`

**Comment by gcasella** [comment]
Hey There @mikat-gh I can get the API working fine for get-session-key.
I have to follow a VERY specific procedure.

I also extended the creation of the UserKey to the API as well so that I don't have to have users log into netbox directly.
However, when I extend this API to write my public key to the model it doesn't seem to import / save it properly. 

I can share some of the changes to the source code if you're interested and to see if this type of implementation might fix this issue permanently?
![image](https://user-images.githubusercontent.com/7719536/205067489-54794335-478e-4a3f-88d4-889a57d8c237.png)
![image](https://user-images.githubusercontent.com/7719536/205067522-d0809158-e1e3-4f13-b3d6-8958878dd8e0.png)

**Comment by gcasella** [comment]
**api/urls.py**
`
from netbox.api.routers import NetBoxRouter
from . import views


router = NetBoxRouter()
router.APIRootView = views.SecretsRootView

# Secrets
router.register('secret-roles', views.SecretRoleViewSet)
router.register('secrets', views.SecretViewSet)

# Miscellaneous
router.register('get-session-key', views.GetSessionKeyViewSet, basename='get-session-key')
router.register('generate-rsa-key-pair', views.GenerateRSAKeyPairViewSet, basename='generate-rsa-key-pair')

router.register('create-user-key', views.GenerateUserKeyViewSet, basename='create-user-key')
router.register('delete-user-key', views.DeleteUserKey, basename='delete-user-key')

urlpatterns = router.urls
`

**api/view.py**
* Added
`
from netbox_secretstore.utils import encrypt_master_key, decrypt_master_key, generate_random_key

class GenerateUserKeyViewSet(ViewSet):
    """
    This endpoint can be used to generate a new RSA key pair. The keys are returned in PEM format.

        {
            "public_key": "<public key>",
            "private_key": "<private key>"
        }
    """
    permission_classes = [IsAuthenticated]

    def create(self, request):
        # Determine what size key to generate
        try:
            key_size = request.data.get('key_size', 2048)
            key_size = int(key_size)
        except ValueError as e:
            key_size = 2048

        if key_size not in range(2048, 4097, 256):
            key_size = 2048

        # Export RSA private and public keys in PEM format
        key = RSA.generate(key_size)
        private_key = key.exportKey('PEM')
        public_key = key.publickey().exportKey('PEM')

        # Validate user key, if UserKey exists, replace RSA KeyPair with the KeyPair created above, and send back the Private Key via API.
        try:
            user_key = UserKey.objects.get(user=request.user)
            user_key.clean()
            user_key.public_key = public_key.decode()
            ## Added to always generate a new master_key and automatically always activate the UserKey
            ## Not sure if this is really needed.
            ## Ran into issue where UserKey may be either Active / Inactive (random reproduction)
            master_key = generate_random_key()
            user_key.activate(master_key)
            user_key.save()

            return Response({
                'details': 'Existing UserKey. Generating New Key Pair.',
                'private_key': private_key.decode(),
                'userkey_id': user_key.id
            })

        # If the UserKey doesn't exist, create a new UserKey with the RSA KeyPair created above. Send back Private Key via API.
        except UserKey.DoesNotExist:
            user_key = UserKey(user=request.user)
            user_key.clean()
            user_key.public_key = public_key.decode()
            ## Added to always generate a new master_key and automatically always activate the UserKey
            ## Not sure if this is really needed.
            ## Ran into issue where UserKey may be either Active / Inactive (random reproduction)
            master_key = generate_random_key()
            user_key.activate(master_key)
            user_key.save()

            return Response({
                'details': 'New UserKey Created for current user.',
                'private_key': private_key.decode(),
                'userkey_id': user_key.id
            })


class DeleteUserKey(ViewSet):
    """
    This endpoint can be used to generate a new RSA key pair. The keys are returned in PEM format.

        {
            "public_key": "<public key>",
            "private_key": "<private key>"
        }
    """
    permission_classes = [IsAuthenticated]

    def create(self, request, *args, **kwargs):
        # Validate user key
        try:
            user_key = UserKey.objects.get(user=request.user)
            user_key.delete()
            return Response({
                'details': f"{request.user} UserKey/SessionKey removed.",
            })

        except UserKey.DoesNotExist:
            return HttpResponseBadRequest(ERR_USERKEY_MISSING)
`

(For fun i addedd a "Delete" userKey view as well.
Below you can see a screenshot of my Postman flow;

Just thought I would share this with you to help out where I can @mikat-gh 


If this looks good to you, I don't mind opening a PR to get this put in the release, my NetBox version is 3.3.7

**Comment by gcasella** [comment]
@DanSheps tagging you as i see you are the owner, i was accidentally tagging mikat-gh

**Comment by DanSheps** [comment]
The Unicode decode error is because the key was originally stored in plain-text because of an error.

I am tempted to just move database encryption to a single shared key stored in the database

**Comment by DanSheps** [comment]
The Unicode decode error is because the key was originally stored in plain-text because of an error.

I am tempted to just move database encryption to a single shared key stored in the database with a passphrase in the config file to remove the need for the endpoints.  This will require a migration however to decrypt all secrets and re-encrypt them.

**Comment by gcasella** [comment]
I like the idea. 
My use case for this is to store a shared secret, not really intended on a per device basis but more like a common root password for all devices. 
And to view the password. I was thinking of using thus package

**Comment by mikat-gh** [comment]
I'm fine with any improvement.

Until there is a better way, it would be nice to have #92 merged, or fix the documentation to give a working example. I couldn't figure out how to the request should be done as application/json.
